"""Foundation substrate for all palace-mcp extractors (GIM-101a).

Import the public surface from submodules as needed.
"""

from palace_mcp.extractors.foundation.errors import ExtractorError, ExtractorErrorCode
from palace_mcp.extractors.foundation.delta_resolution import (
    DeltaResolutionBaseline,
    EdgeDelta,
    EdgeSnapshot,
    PublicApiDelta,
    PublicApiSnapshot,
    ResolvedDelta,
    SeedDelta,
    SymbolDelta,
    SymbolSnapshot,
    capture_delta_resolution_baseline,
    delta_resolution_artifact_path,
    diff_delta_snapshots,
    read_delta_resolution_baseline_artifact,
    resolve_delta_resolution,
    write_delta_resolution_baseline_artifact,
)
from palace_mcp.extractors.foundation.baseline import (
    BASELINE_STATUS_VALID,
    ExtractorBaseline,
    build_valid_extractor_baseline,
    delete_extractor_baseline,
    load_extractor_baseline,
    upsert_extractor_baseline,
)
from palace_mcp.extractors.foundation.models import (
    Ecosystem,
    EvictionRecord,
    ExternalDependency,
    IngestCheckpoint,
    Language,
    PublicApiArtifactKind,
    PublicApiSurface,
    PublicApiSymbol,
    PublicApiSymbolKind,
    PublicApiVisibility,
    SourceType,
    SymbolKind,
    SymbolOccurrence,
    SymbolOccurrenceShadow,
)
from palace_mcp.extractors.foundation.incremental_scope import (
    SwiftDeltaScope,
    derive_swift_delta_scope,
)
from palace_mcp.extractors.foundation.semgrep_runner import (
    SemgrepConfigInvalidError,
    SemgrepInternalError,
    SemgrepTargetError,
    run_semgrep,
)
from palace_mcp.extractors.foundation.walk import (
    DEFAULT_STOP_DIRS,
    DEFAULT_STOP_PREFIXES,
    should_skip_path,
    walk_repo,
)

__all__ = [
    "DEFAULT_STOP_DIRS",
    "DEFAULT_STOP_PREFIXES",
    "BASELINE_STATUS_VALID",
    "DeltaResolutionBaseline",
    "Ecosystem",
    "EdgeDelta",
    "EdgeSnapshot",
    "EvictionRecord",
    "ExtractorBaseline",
    "ExtractorError",
    "ExtractorErrorCode",
    "ExternalDependency",
    "IngestCheckpoint",
    "Language",
    "PublicApiDelta",
    "PublicApiArtifactKind",
    "PublicApiSnapshot",
    "PublicApiSurface",
    "PublicApiSymbol",
    "PublicApiSymbolKind",
    "PublicApiVisibility",
    "ResolvedDelta",
    "run_semgrep",
    "SemgrepConfigInvalidError",
    "SemgrepInternalError",
    "SemgrepTargetError",
    "SeedDelta",
    "should_skip_path",
    "SourceType",
    "SymbolDelta",
    "SymbolKind",
    "SymbolOccurrence",
    "SymbolOccurrenceShadow",
    "SymbolSnapshot",
    "SwiftDeltaScope",
    "capture_delta_resolution_baseline",
    "build_valid_extractor_baseline",
    "delete_extractor_baseline",
    "derive_swift_delta_scope",
    "delta_resolution_artifact_path",
    "diff_delta_snapshots",
    "load_extractor_baseline",
    "read_delta_resolution_baseline_artifact",
    "resolve_delta_resolution",
    "upsert_extractor_baseline",
    "write_delta_resolution_baseline_artifact",
    "walk_repo",
]
