"""simpleperf protobuf parser for hot_path_profiler."""

from __future__ import annotations

import struct
from pathlib import Path
from typing import Any

from google.protobuf.message import DecodeError

from palace_mcp.extractors.base import ExtractorRuntimeError
from palace_mcp.extractors.hot_path_profiler.models import HotPathSample, HotPathSummary
from palace_mcp.proto import simpleperf_report_pb2

DEFAULT_THRESHOLD = 0.05
MAX_SIMPLEPERF_SIZE_MB = 64
SIMPLEPERF_MAGIC = b"SIMPLEPERF"
SIMPLEPERF_VERSION = 1


def is_simpleperf_trace(trace_path: Path) -> bool:
    """Return True when the file has the simpleperf report-sample header."""

    with trace_path.open("rb") as trace_file:
        return trace_file.read(len(SIMPLEPERF_MAGIC)) == SIMPLEPERF_MAGIC


def parse_simpleperf_trace(
    trace_path: Path,
) -> tuple[HotPathSummary, list[HotPathSample]]:
    """Parse one simpleperf protobuf report generated by report-sample."""

    size = trace_path.stat().st_size
    if size > MAX_SIMPLEPERF_SIZE_MB * 1024 * 1024:
        raise ExtractorRuntimeError(
            f"simpleperf trace {trace_path} exceeds {MAX_SIMPLEPERF_SIZE_MB} MB"
        )

    payload = trace_path.read_bytes()
    if len(payload) < len(SIMPLEPERF_MAGIC) + 2:
        raise ExtractorRuntimeError(f"simpleperf trace {trace_path} is truncated")
    if payload[: len(SIMPLEPERF_MAGIC)] != SIMPLEPERF_MAGIC:
        raise ExtractorRuntimeError(
            f"simpleperf trace {trace_path} is missing SIMPLEPERF header"
        )

    version = struct.unpack_from("<H", payload, len(SIMPLEPERF_MAGIC))[0]
    if version != SIMPLEPERF_VERSION:
        raise ExtractorRuntimeError(
            f"unsupported simpleperf trace version {version} in {trace_path}"
        )

    files: dict[int, Any] = {}
    threads: dict[int, Any] = {}
    aggregated: dict[tuple[str, str | None], HotPathSample] = {}
    total_cpu_samples = 0
    offset = len(SIMPLEPERF_MAGIC) + 2

    while offset + 4 <= len(payload):
        record_size = struct.unpack_from("<I", payload, offset)[0]
        offset += 4
        if record_size == 0:
            break
        record_end = offset + record_size
        if record_end > len(payload):
            raise ExtractorRuntimeError(
                f"simpleperf trace {trace_path} has truncated record payload"
            )
        record = simpleperf_report_pb2.Record()  # type: ignore[attr-defined]
        try:
            record.ParseFromString(payload[offset:record_end])
        except DecodeError as exc:
            raise ExtractorRuntimeError(
                f"failed to parse simpleperf record in {trace_path}: {exc}"
            ) from exc
        offset = record_end

        record_kind = record.WhichOneof("record_data")
        if record_kind == "file":
            files[record.file.id] = record.file
        elif record_kind == "thread":
            threads[record.thread.thread_id] = record.thread
        elif record_kind == "sample":
            sample = record.sample
            symbol_name = _resolve_symbol_name(sample, files)
            thread_name = _thread_name(sample.thread_id, threads)
            cpu_samples = max(int(sample.event_count), 1)
            total_cpu_samples += cpu_samples
            key = (symbol_name, thread_name)
            previous = aggregated.get(key)
            if previous is None:
                aggregated[key] = HotPathSample(
                    trace_id=trace_path.stem,
                    source_format="simpleperf",
                    symbol_name=symbol_name,
                    cpu_samples=cpu_samples,
                    wall_ms=0,
                    total_samples_in_trace=1,
                    total_wall_ms_in_trace=0,
                    thread_name=thread_name,
                )
            else:
                aggregated[key] = previous.model_copy(
                    update={"cpu_samples": previous.cpu_samples + cpu_samples}
                )

    if total_cpu_samples <= 0 or not aggregated:
        raise ExtractorRuntimeError(
            f"simpleperf trace {trace_path} produced zero samples"
        )

    samples = [
        sample.model_copy(
            update={
                "total_samples_in_trace": total_cpu_samples,
                "total_wall_ms_in_trace": 0,
            }
        )
        for sample in aggregated.values()
    ]
    samples.sort(
        key=lambda sample: (-sample.cpu_samples, -sample.wall_ms, sample.symbol_name)
    )

    summary = HotPathSummary(
        trace_id=trace_path.stem,
        source_format="simpleperf",
        total_cpu_samples=total_cpu_samples,
        total_wall_ms=0,
        hot_function_count=sum(
            1 for sample in samples if sample.cpu_share >= DEFAULT_THRESHOLD
        ),
        threshold_cpu_share=DEFAULT_THRESHOLD,
    )
    return summary, samples


def _resolve_symbol_name(
    sample: Any,
    files: dict[int, Any],
) -> str:
    if sample.callchain:
        frame = sample.callchain[0]
        file_entry = files.get(frame.file_id)
        if file_entry is not None:
            if 0 <= frame.symbol_id < len(file_entry.symbol):
                symbol = file_entry.symbol[frame.symbol_id]
                if symbol.strip():
                    return str(symbol.strip())
            if 0 <= frame.symbol_id < len(file_entry.mangled_symbol):
                symbol = file_entry.mangled_symbol[frame.symbol_id]
                if symbol.strip():
                    return str(symbol.strip())
            if file_entry.path.strip():
                return str(f"{file_entry.path}!0x{frame.vaddr_in_file:x}")
    return "unknown"


def _thread_name(
    thread_id: int,
    threads: dict[int, Any],
) -> str | None:
    thread = threads.get(thread_id)
    if thread is None:
        return None
    value = thread.thread_name.strip()
    return value or None
