"""Unit tests for foundation.delta_resolution."""

from __future__ import annotations

from pathlib import Path

from palace_mcp.extractors.foundation.delta_resolution import (
    DeltaResolutionBaseline,
    EdgeDelta,
    EdgeSnapshot,
    PublicApiDelta,
    PublicApiSnapshot,
    SeedDelta,
    SymbolDelta,
    SymbolSnapshot,
    diff_delta_snapshots,
    read_delta_resolution_baseline_artifact,
    write_delta_resolution_baseline_artifact,
)


def test_diff_delta_snapshots_classifies_symbol_edge_seed_and_public_api_changes() -> (
    None
):
    baseline = DeltaResolutionBaseline(
        group_id="project/delta-mini",
        project="delta-mini",
        previous_commit_sha="commit-old",
        affected_paths=frozenset(
            {
                "Artifacts/FinanceKit.swiftinterface",
                "Sources/Core/Wallet.swift",
                "Sources/Legacy.swift",
                "Sources/Wallet.swift",
            }
        ),
        symbols=(
            SymbolSnapshot(
                qualified_name="Wallet",
                file_path="Sources/Wallet.swift",
                module_name="FinanceKit",
                access_modifier="public",
            ),
            SymbolSnapshot(
                qualified_name="Wallet.balance()",
                file_path="Sources/Wallet.swift",
                module_name="FinanceKit",
                access_modifier="public",
            ),
            SymbolSnapshot(
                qualified_name="LegacyUtility",
                file_path="Sources/Legacy.swift",
                module_name="FinanceKit",
                access_modifier="internal",
            ),
        ),
        edges=(
            EdgeSnapshot(
                source="Wallet.balance()",
                target="Formatter.format()",
                relationship_type="CALLS",
            ),
            EdgeSnapshot(
                source="Wallet.balance()",
                target="Money",
                relationship_type="REFERENCES",
            ),
            EdgeSnapshot(
                source="LegacyUtility",
                target="AnyBalanceProtocol",
                relationship_type="EXISTENTIAL_USE",
            ),
        ),
        public_api_symbols=(
            PublicApiSnapshot(
                fqn="Wallet",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-wallet-old",
            ),
            PublicApiSnapshot(
                fqn="Wallet.balance()",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-balance-old",
            ),
            PublicApiSnapshot(
                fqn="staleExport()",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-stale-old",
            ),
        ),
    )

    resolved = diff_delta_snapshots(
        baseline=baseline,
        current_symbols=(
            SymbolSnapshot(
                qualified_name="Wallet",
                file_path="Sources/Core/Wallet.swift",
                module_name="CoreKit",
                access_modifier="public",
            ),
            SymbolSnapshot(
                qualified_name="Wallet.balance()",
                file_path="Sources/Core/Wallet.swift",
                module_name="CoreKit",
                access_modifier="internal",
            ),
            SymbolSnapshot(
                qualified_name="Wallet.owner()",
                file_path="Sources/Core/Wallet.swift",
                module_name="CoreKit",
                access_modifier="internal",
            ),
        ),
        current_edges=(
            EdgeSnapshot(
                source="Wallet.balance()",
                target="Currency",
                relationship_type="REFERENCES",
            ),
            EdgeSnapshot(
                source="Wallet.owner()",
                target="Wallet",
                relationship_type="EXTENDS",
            ),
        ),
        current_public_api_symbols=(
            PublicApiSnapshot(
                fqn="Wallet",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-wallet-new",
            ),
            PublicApiSnapshot(
                fqn="Wallet.balance()",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-balance-old",
            ),
            PublicApiSnapshot(
                fqn="Wallet.owner()",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-owner-new",
            ),
        ),
    )

    assert resolved.symbol_deltas == (
        SymbolDelta(
            qualified_name="Wallet.owner()",
            change_kind="added",
            current_file_path="Sources/Core/Wallet.swift",
            current_module_name="CoreKit",
        ),
        SymbolDelta(
            qualified_name="Wallet",
            change_kind="moved",
            previous_file_path="Sources/Wallet.swift",
            current_file_path="Sources/Core/Wallet.swift",
            previous_module_name="FinanceKit",
            current_module_name="CoreKit",
        ),
        SymbolDelta(
            qualified_name="Wallet.balance()",
            change_kind="moved",
            previous_file_path="Sources/Wallet.swift",
            current_file_path="Sources/Core/Wallet.swift",
            previous_module_name="FinanceKit",
            current_module_name="CoreKit",
        ),
        SymbolDelta(
            qualified_name="LegacyUtility",
            change_kind="removed",
            previous_file_path="Sources/Legacy.swift",
            previous_module_name="FinanceKit",
        ),
    )
    assert resolved.edge_deltas == (
        EdgeDelta(
            source="Wallet.owner()",
            target="Wallet",
            relationship_type="EXTENDS",
            change_kind="added",
        ),
        EdgeDelta(
            source="Wallet.balance()",
            target="Currency",
            relationship_type="REFERENCES",
            change_kind="added",
        ),
        EdgeDelta(
            source="Wallet.balance()",
            target="Formatter.format()",
            relationship_type="CALLS",
            change_kind="removed",
        ),
        EdgeDelta(
            source="LegacyUtility",
            target="AnyBalanceProtocol",
            relationship_type="EXISTENTIAL_USE",
            change_kind="removed",
        ),
        EdgeDelta(
            source="Wallet.balance()",
            target="Money",
            relationship_type="REFERENCES",
            change_kind="removed",
        ),
    )
    assert resolved.seed_deltas == (
        SeedDelta(
            qualified_name="Wallet.balance()",
            previous_is_seed=True,
            current_is_seed=False,
        ),
    )
    assert resolved.public_api_deltas == (
        PublicApiDelta(
            fqn="Wallet.owner()",
            module_name="FinanceKit",
            source_artifact_path="Artifacts/FinanceKit.swiftinterface",
            change_kind="added",
            current_signature_hash="sig-owner-new",
        ),
        PublicApiDelta(
            fqn="staleExport()",
            module_name="FinanceKit",
            source_artifact_path="Artifacts/FinanceKit.swiftinterface",
            change_kind="removed",
            previous_signature_hash="sig-stale-old",
        ),
        PublicApiDelta(
            fqn="Wallet",
            module_name="FinanceKit",
            source_artifact_path="Artifacts/FinanceKit.swiftinterface",
            change_kind="signature_changed",
            previous_signature_hash="sig-wallet-old",
            current_signature_hash="sig-wallet-new",
        ),
    )


def test_delta_resolution_baseline_artifact_round_trips(tmp_path: Path) -> None:
    baseline = DeltaResolutionBaseline(
        group_id="project/delta-mini",
        project="delta-mini",
        previous_commit_sha="commit-old",
        affected_paths=frozenset({"Sources/Wallet.swift", "Sources/Legacy.swift"}),
        symbols=(
            SymbolSnapshot(
                qualified_name="Wallet",
                file_path="Sources/Wallet.swift",
                module_name="FinanceKit",
                access_modifier="public",
            ),
        ),
        edges=(
            EdgeSnapshot(
                source="Wallet.balance()",
                target="Formatter.format()",
                relationship_type="CALLS",
            ),
        ),
        public_api_symbols=(
            PublicApiSnapshot(
                fqn="Wallet",
                module_name="FinanceKit",
                source_artifact_path="Artifacts/FinanceKit.swiftinterface",
                signature_hash="sig-wallet-old",
            ),
        ),
    )

    write_delta_resolution_baseline_artifact(
        repo_path=tmp_path,
        run_id="run-symbol-index",
        baseline=baseline,
    )

    loaded = read_delta_resolution_baseline_artifact(
        repo_path=tmp_path,
        run_id="run-symbol-index",
    )

    assert loaded == baseline
